# Generated by Django 2.2.5 on 2020-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
